vich_uploader:
  db_driver: orm

  mappings:
    projets_images:
      uri_prefix: /uploads/projets
      upload_destination: "%kernel.project_dir%/public/uploads/projets"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    actualites_images:
      uri_prefix: /uploads/actualites
      upload_destination: "%kernel.project_dir%/public/uploads/actualites"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    temoignages_images:
      uri_prefix: /uploads/temoignages
      upload_destination: "%kernel.project_dir%/public/uploads/temoignages"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
